export type MediaKind =
  | "plate"
  | "slot"
  | "before"
  | "after"
  | "front"
  | "back"
  | "left"
  | "right"
  | "before_front"
  | "before_back"
  | "before_left"
  | "before_right"
  | "after_front"
  | "after_back"
  | "after_left"
  | "after_right";
